model:
  name: "DiffusionModel"
  params:
    history_steps: 1
    state_dict_path: /bask/projects/v/vjgo8416-climate/shared/cloudcasting-validation/ocf-diffusion/best-model-epoch-1-loss-0.101-state-dict.pt
validation:
  data_path: "/bask/projects/v/vjgo8416-climate/shared/data/eumetsat/testing2022/2022_test_nonhrv.zarr"
  wandb_project_name: "cloudcasting"
  wandb_run_name: "DiffusionModel-validation"
  nan_to_num: False
  batch_size: 2
  num_workers: 0